---
# tasks file for nclu
- name: add nclu group commands
  nclu:
    commands:
      - "{{ item }}"
  notify:
    - commit commands
  with_items: "{{ cumulus_nclu.group_commands }}"

- name: add nclu host commands
  nclu:
    commands:
      - "{{ item }}"
  notify:
    - commit commands
  with_items: "{{ cumulus_nclu.commands }}"

- name: add nclu template group commands
  nclu:
    template: |
      - "{{ item }}"
  notify:
    - commit commands
  with_items: "{{ cumulus_nclu.template_group_commands }}"

- name: add nclu template host commands
  nclu:
    template: |
      - "{{ item }}"
  notify:
    - commit commands
  with_items: "{{ cumulus_nclu.template_commands }}"
